关于异常的最佳实践：
[MSDN Modern C++ best practices for exceptions and error handling](https://learn.microsoft.com/en-us/cpp/cpp/errors-and-exception-handling-modern-cpp?view=msvc-170)

- 断言检查不应该发生的错误，异常检查可能发生的错误。
- 什么时候使用异常： 
   - 如果「错误检测函数」和「错误处理函数」间隔很远，使用异常
   - 如果「错误处理代码」和「错误检测代码」很近；或处于性能关键的循环，谨慎使用异常
- 总是用引用来捕获异常

注：如果一个函数被标记为 `noexcept`，函数内部出现了异常，程序 `runtime`会直接调用 `std::terminate`终止。函数外部不可能捕获到异常。


异常于 RAII：
异常发生时，局部变量的析构函数会被正确地调用，因此可以放心的使用 RAII。
```cpp
class Resource 
{
    Resource() 
    {
        std::cout << "init." << std::endl;
    }
    ~Resource() 
    {
        std::cout << "free." << std::endl;
    }
};

void foo() 
{
    Resource r;
    throw std::runtime_error("");
}

int main() 
{
    try 
    {
        foo()
    }
    catch (std::excption & e) {}
}
```
